### ISSUE TITLE
BASIC-SENDER class definition errors out in CLISP

### ISSUE THREAD

**Issue by quicklisp** [hraban/log5#1]
`basic-sender` has a slot defined with this option:

```
(message-creator :reader message-creator
  :initargs 'basic-message-creator
  :writer %set-message-creator)
```

Should that be `:initarg basic-message-creator` instead? `:initargs` is not defined as a slot option in vanilla CL.

**Comment by gwkkwg** [comment]
Ack! You are so right. The quote before basic-message-creator was wrong too. thanks. fixed.

**Comment by gwkkwg** [comment]
Hmmm, closed before my comment!

**Comment by quicklisp** [comment]
I can confirm that it builds fine in CLISP now, thanks!

**Comment by gwkkwg** [comment]
Thank you!
